version: "3.8"
# services:
#   blog_app:
#     build:
#       context: . # The path of the Dockerfile
#     volumes:
#       - .:/var/www/html
#     # depends_on:
#     #   - blog_db
#     working_dir: /var/www/html
#     environment:
#       SERVICE_NAME: k8s-project-article
#       # DB_CONNECTION: mysql
#       # DB_DRIVER: mysql
#       # DB_HOST: blog_db
#       # DB_PORT: 3306
#     networks:
#       - app_network

#   blog_nginx:
#     build:
#       context: ./docker-nginx/. # The path of the Dockerfile
#     volumes:
#     - "./public:/usr/src/app/public"
#     environment:
#       NGINX_FPM_HOST: blog_app
#       NGINX_ROOT: /usr/src/app/public
#     ports:
#       - "8000:8001"
#     depends_on:
#       - blog_app
#     networks:
#       - app_network

#   # blog_db:
#   #   image: mysql:5
#   #   restart: always
#   #   environment:
#   #     MYSQL_DATABASE: blog
#   #     MYSQL_ROOT_PASSWORD: root
#   #     MYSQL_USER: root
#   #     MYSQL_PASSWORD: root
#   #   ports:
#   #     - "3306:3306"
#   #   volumes:
#   #     - "./storage/db-data:/var/lib/mysql"
#   #   networks:
#   #     - app_network

# networks:
#   app_network:
#     driver: bridge

services:
  nginx:
    image: nginx:latest
    ports:
      - 8080:80
    volumes:
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    volumes_from:
      - php

  php:
    build: ./docker/php/
    volumes:
      - .:/var/www/html
      - ./docker/php/custom.ini:/usr/local/etc/php/conf.d/custom.ini
    # links:
    #   - database
    environment:
      - DB_PORT=8889
      - DB_HOST=192.168.50.101
