version: "3.8"
services:
  blog_app:
    build:
      context: . # The path of the Dockerfile
    volumes:
      - .:/usr/src/app
    # depends_on:
    #   - blog_db
    working_dir: /usr/src/app
    environment:
      SERVICE_NAME: k8s-project-article
      # DB_CONNECTION: mysql
      # DB_DRIVER: mysql
      # DB_HOST: blog_db
      # DB_PORT: 3306
    networks:
      - app_network

  blog_nginx:
    build:
      context: ./docker-nginx/. # The path of the Dockerfile
    volumes:
    - "./public:/usr/src/app/public"
    environment:
      NGINX_FPM_HOST: blog_app
      NGINX_ROOT: /usr/src/app/public
    ports:
      - "8000:80"
    depends_on:
      - blog_app
    networks:
      - app_network

networks:
  app_network:
    driver: bridge