FROM mariadb:10.2
RUN apt-get update && apt-get install -y nano 
# CMD ["mysqld", "--innodb_force_recovery = 1"]
# CMD ["mysqld", "--innodb-flush-method=fsync", "--innodb-use-native-aio=0", "--log_bin=ON"]